using System;
using System.Collections.Generic;
using System.Globalization;

namespace ClipboardSyncWin;

internal static class AppText
{
    private enum Language
    {
        English,
        Chinese,
        Korean,
        Japanese
    }

    private static readonly Language CurrentLanguage = ResolveLanguage();

    private static readonly IReadOnlyDictionary<Language, IReadOnlyDictionary<string, string>> Values =
        new Dictionary<Language, IReadOnlyDictionary<string, string>>
        {
            [Language.English] = new Dictionary<string, string>
            {
                ["app.name"] = "Clipboard Sync",
                ["state.enabled"] = "Enabled",
                ["state.disabled"] = "Disabled",
                ["state.unknown"] = "Unknown",
                ["device.unknown"] = "Unknown Device",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "Status: {0}",
                ["status.stopped"] = "stopped",
                ["status.copyFilesFirst"] = "copy files first",
                ["status.fileTransferStarted"] = "file transfer started",
                ["status.filesReceived"] = "files received",
                ["status.setSyncPassword"] = "set sync password",
                ["status.setServerLanIp"] = "set server LAN IP",
                ["status.useLanIp"] = "use LAN IP, not 127.0.0.1",
                ["status.encryptionFailed"] = "encryption failed",
                ["status.clipboardPayloadTooLarge"] = "clipboard payload too large",
                ["status.inputPayloadTooLarge"] = "input payload too large",
                ["status.restoreHistoryFailed"] = "failed to restore history item",
                ["status.folderUnsupported"] = "folder clipboard is not supported",
                ["status.fileTooLarge"] = "file over 10 MB skipped",
                ["status.fileReadFailed"] = "file clipboard read failed",
                ["status.imageTooLarge"] = "image over 10 MB skipped",
                ["status.sendFailed"] = "send failed",
                ["status.connecting"] = "connecting {0}:{1}",
                ["status.connected"] = "connected {0}:{1}",
                ["status.disconnectedRetrying"] = "disconnected; retrying",
                ["status.messageHandlerFailed"] = "message handler failed",
                ["status.serverPeers"] = "server {0}, {1} peer(s)",
                ["status.serverError"] = "server error: {0}",
                ["status.serverAcceptFailed"] = "server accept failed",
                ["menu.clipboardHistory"] = "Clipboard History",
                ["menu.noClipboardHistory"] = "No clipboard history",
                ["menu.clearClipboardHistory"] = "Clear Clipboard History",
                ["menu.sendFiles"] = "Send Files from Clipboard",
                ["menu.enableInputSharing"] = "Enable Input Sharing",
                ["menu.controlDevice"] = "Control Device",
                ["menu.controlDeviceWithTitle"] = "Control Device: {0}",
                ["menu.screenLayout"] = "Screen Layout...",
                ["menu.clientMode"] = "Client mode",
                ["menu.serverMode"] = "Server mode",
                ["menu.configure"] = "Configure...",
                ["menu.checkForUpdates"] = "Check for Updates...",
                ["menu.about"] = "About Clipboard Sync...",
                ["menu.homepage"] = "Project Homepage",
                ["menu.start"] = "Start",
                ["menu.restart"] = "Restart",
                ["menu.stop"] = "Stop",
                ["menu.launchAtLogin"] = "Launch at Login",
                ["menu.exit"] = "Exit",
                ["about.title"] = "About {0}",
                ["about.message"] = "{0}\nVersion {1}",
                ["edge.left"] = "Left",
                ["edge.right"] = "Right",
                ["edge.top"] = "Top",
                ["edge.bottom"] = "Bottom",
                ["history.text"] = "Text",
                ["history.textWithPreview"] = "Text: {0}",
                ["history.image"] = "Image: {0}",
                ["history.files"] = "Files: {0}{1}",
                ["input.off"] = "Input Sharing: off",
                ["input.waitingPeer"] = "Input Sharing: waiting for peer",
                ["input.peerDisabled"] = "Input Sharing: peer disabled",
                ["input.waitingPeerScreen"] = "Input Sharing: waiting for peer screen",
                ["input.controllingPeer"] = "Input Sharing: controlling peer ({0})",
                ["input.receiving"] = "Input Sharing: receiving input",
                ["input.ready"] = "Input Sharing: ready",
                ["settings.title"] = "Clipboard Sync Settings",
                ["settings.mode"] = "Mode",
                ["settings.host"] = "Host",
                ["settings.port"] = "Port",
                ["settings.password"] = "Password",
                ["settings.input"] = "Input",
                ["settings.scroll"] = "Scroll",
                ["settings.modifierKeys"] = "Keys",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "Client",
                ["settings.server"] = "Server",
                ["settings.enableInputSharing"] = "Enable Input Sharing",
                ["settings.reverseVerticalScroll"] = "Reverse Vertical Scroll",
                ["settings.save"] = "Save",
                ["settings.cancel"] = "Cancel",
                ["settings.hostClientHint"] = "Enter the LAN IP shown on the server.",
                ["settings.hostServerHint"] = "Share this address with clients on the same LAN.",
                ["settings.validationHost"] = "Enter the server LAN IP for client mode.",
                ["settings.validationLoopback"] = "Use the server machine's LAN IP, not 127.0.0.1.",
                ["settings.validationPassword"] = "Enter the same sync password on every device.",
                ["layout.title"] = "Screen Layout",
                ["layout.subtitle"] = "Drag each screen to match how your machines sit relative to each other.",
                ["layout.done"] = "Done",
                ["layout.disconnected"] = "Disconnected",
                ["layout.inputDisabled"] = "Input Sharing Off",
                ["layout.forgetDevice"] = "Forget This Device",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "Auto-update is not configured yet. Generate a NetSparkle Ed25519 keypair and replace the Windows updater public key before release.",
                ["status.betaExpired"] = "beta ended, update required",
                ["beta.expiredTitle"] = "Beta Period Ended",
                ["beta.expiredMessage"] = "This beta build's 30-day trial has ended. Please check for updates to keep using Clipboard Sync.",
                ["beta.checkNowQuestion"] = "Check for updates now?"
            },
            [Language.Chinese] = new Dictionary<string, string>
            {
                ["app.name"] = "剪贴板同步",
                ["state.enabled"] = "已启用",
                ["state.disabled"] = "已禁用",
                ["state.unknown"] = "未知",
                ["device.unknown"] = "未知设备",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "状态：{0}",
                ["status.stopped"] = "已停止",
                ["status.copyFilesFirst"] = "请先复制文件",
                ["status.fileTransferStarted"] = "文件传输已开始",
                ["status.filesReceived"] = "已收到文件",
                ["status.setSyncPassword"] = "请设置同步密码",
                ["status.setServerLanIp"] = "请设置服务器局域网 IP",
                ["status.useLanIp"] = "请使用局域网 IP，不要用 127.0.0.1",
                ["status.encryptionFailed"] = "加密失败",
                ["status.clipboardPayloadTooLarge"] = "剪贴板内容过大",
                ["status.inputPayloadTooLarge"] = "输入数据过大",
                ["status.restoreHistoryFailed"] = "恢复历史记录失败",
                ["status.folderUnsupported"] = "不支持文件夹剪贴板",
                ["status.fileTooLarge"] = "文件超过 10 MB，已跳过",
                ["status.fileReadFailed"] = "读取文件剪贴板失败",
                ["status.imageTooLarge"] = "图片超过 10 MB，已跳过",
                ["status.sendFailed"] = "发送失败",
                ["status.connecting"] = "正在连接 {0}:{1}",
                ["status.connected"] = "已连接 {0}:{1}",
                ["status.disconnectedRetrying"] = "已断开，正在重试",
                ["status.messageHandlerFailed"] = "消息处理失败",
                ["status.serverPeers"] = "服务器 {0}，{1} 个对端",
                ["status.serverError"] = "服务器错误：{0}",
                ["status.serverAcceptFailed"] = "服务器接受连接失败",
                ["menu.clipboardHistory"] = "剪贴板历史",
                ["menu.noClipboardHistory"] = "无剪贴板历史",
                ["menu.clearClipboardHistory"] = "清除剪贴板历史",
                ["menu.sendFiles"] = "从剪贴板发送文件",
                ["menu.enableInputSharing"] = "启用输入共享",
                ["menu.controlDevice"] = "控制设备",
                ["menu.controlDeviceWithTitle"] = "控制设备：{0}",
                ["menu.screenLayout"] = "屏幕布局...",
                ["menu.clientMode"] = "客户端模式",
                ["menu.serverMode"] = "服务器模式",
                ["menu.configure"] = "设置...",
                ["menu.checkForUpdates"] = "检查更新...",
                ["menu.about"] = "关于剪贴板同步...",
                ["menu.homepage"] = "项目主页",
                ["menu.start"] = "启动",
                ["menu.restart"] = "重启",
                ["menu.stop"] = "停止",
                ["menu.launchAtLogin"] = "登录时自动启动",
                ["menu.exit"] = "退出",
                ["about.title"] = "关于{0}",
                ["about.message"] = "{0}\n版本 {1}",
                ["edge.left"] = "左侧",
                ["edge.right"] = "右侧",
                ["edge.top"] = "上方",
                ["edge.bottom"] = "下方",
                ["history.text"] = "文本",
                ["history.textWithPreview"] = "文本：{0}",
                ["history.image"] = "图片：{0}",
                ["history.files"] = "文件：{0}{1}",
                ["input.off"] = "输入共享：关闭",
                ["input.waitingPeer"] = "输入共享：等待对端",
                ["input.peerDisabled"] = "输入共享：对端已禁用",
                ["input.waitingPeerScreen"] = "输入共享：等待对端屏幕信息",
                ["input.controllingPeer"] = "输入共享：正在控制对端（{0}）",
                ["input.receiving"] = "输入共享：正在接收输入",
                ["input.ready"] = "输入共享：就绪",
                ["settings.title"] = "剪贴板同步设置",
                ["settings.mode"] = "模式",
                ["settings.host"] = "主机",
                ["settings.port"] = "端口",
                ["settings.password"] = "密码",
                ["settings.input"] = "输入",
                ["settings.scroll"] = "滚动",
                ["settings.modifierKeys"] = "按键",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "客户端",
                ["settings.server"] = "服务器",
                ["settings.enableInputSharing"] = "启用输入共享",
                ["settings.reverseVerticalScroll"] = "反转垂直滚动",
                ["settings.save"] = "保存",
                ["settings.cancel"] = "取消",
                ["settings.hostClientHint"] = "输入服务器显示的局域网 IP。",
                ["settings.hostServerHint"] = "将此地址分享给同一局域网内的客户端。",
                ["settings.validationHost"] = "请输入客户端模式的服务器局域网 IP。",
                ["settings.validationLoopback"] = "请使用服务器的局域网 IP，不要用 127.0.0.1。",
                ["settings.validationPassword"] = "请在每台设备上输入相同的同步密码。",
                ["layout.title"] = "屏幕布局",
                ["layout.subtitle"] = "拖动每个屏幕以匹配设备之间的实际摆放位置。",
                ["layout.done"] = "完成",
                ["layout.disconnected"] = "已断开",
                ["layout.inputDisabled"] = "输入共享已关闭",
                ["layout.forgetDevice"] = "忘记此设备",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "尚未配置自动更新。发布前请生成 NetSparkle Ed25519 密钥对，并替换 Windows 更新器公钥。",
                ["status.betaExpired"] = "测试已结束，需要更新",
                ["beta.expiredTitle"] = "测试期已结束",
                ["beta.expiredMessage"] = "此测试版本的 30 天试用期已结束，请检查更新以继续使用剪贴板同步。",
                ["beta.checkNowQuestion"] = "现在检查更新吗？"
            },
            [Language.Korean] = new Dictionary<string, string>
            {
                ["app.name"] = "클립보드 동기화",
                ["state.enabled"] = "활성",
                ["state.disabled"] = "비활성",
                ["state.unknown"] = "알 수 없음",
                ["device.unknown"] = "알 수 없는 장치",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "상태: {0}",
                ["status.stopped"] = "중지됨",
                ["status.copyFilesFirst"] = "먼저 파일을 복사하세요",
                ["status.fileTransferStarted"] = "파일 전송 시작됨",
                ["status.filesReceived"] = "파일을 받았습니다",
                ["status.setSyncPassword"] = "동기화 암호를 설정하세요",
                ["status.setServerLanIp"] = "서버 LAN IP를 설정하세요",
                ["status.useLanIp"] = "127.0.0.1 대신 LAN IP를 사용하세요",
                ["status.encryptionFailed"] = "암호화 실패",
                ["status.clipboardPayloadTooLarge"] = "클립보드 데이터가 너무 큼",
                ["status.inputPayloadTooLarge"] = "입력 데이터가 너무 큼",
                ["status.restoreHistoryFailed"] = "기록 항목 복원 실패",
                ["status.folderUnsupported"] = "폴더 클립보드는 지원되지 않음",
                ["status.fileTooLarge"] = "10 MB 초과 파일 건너뜀",
                ["status.fileReadFailed"] = "파일 클립보드 읽기 실패",
                ["status.imageTooLarge"] = "10 MB 초과 이미지 건너뜀",
                ["status.sendFailed"] = "전송 실패",
                ["status.connecting"] = "{0}:{1} 연결 중",
                ["status.connected"] = "{0}:{1} 연결됨",
                ["status.disconnectedRetrying"] = "연결 끊김; 다시 시도 중",
                ["status.messageHandlerFailed"] = "메시지 처리 실패",
                ["status.serverPeers"] = "서버 {0}, 상대 {1}개",
                ["status.serverError"] = "서버 오류: {0}",
                ["status.serverAcceptFailed"] = "서버 연결 수락 실패",
                ["menu.clipboardHistory"] = "클립보드 기록",
                ["menu.noClipboardHistory"] = "클립보드 기록 없음",
                ["menu.clearClipboardHistory"] = "클립보드 기록 지우기",
                ["menu.sendFiles"] = "클립보드에서 파일 보내기",
                ["menu.enableInputSharing"] = "입력 공유 활성화",
                ["menu.controlDevice"] = "제어 장치",
                ["menu.controlDeviceWithTitle"] = "제어 장치: {0}",
                ["menu.screenLayout"] = "화면 레이아웃...",
                ["menu.clientMode"] = "클라이언트 모드",
                ["menu.serverMode"] = "서버 모드",
                ["menu.configure"] = "설정...",
                ["menu.checkForUpdates"] = "업데이트 확인...",
                ["menu.about"] = "클립보드 동기화 정보...",
                ["menu.homepage"] = "프로젝트 홈페이지",
                ["menu.start"] = "시작",
                ["menu.restart"] = "다시 시작",
                ["menu.stop"] = "중지",
                ["menu.launchAtLogin"] = "로그인 시 자동 실행",
                ["menu.exit"] = "종료",
                ["about.title"] = "{0} 정보",
                ["about.message"] = "{0}\n버전 {1}",
                ["edge.left"] = "왼쪽",
                ["edge.right"] = "오른쪽",
                ["edge.top"] = "위",
                ["edge.bottom"] = "아래",
                ["history.text"] = "텍스트",
                ["history.textWithPreview"] = "텍스트: {0}",
                ["history.image"] = "이미지: {0}",
                ["history.files"] = "파일: {0}{1}",
                ["input.off"] = "입력 공유: 꺼짐",
                ["input.waitingPeer"] = "입력 공유: 상대 대기 중",
                ["input.peerDisabled"] = "입력 공유: 상대가 비활성화됨",
                ["input.waitingPeerScreen"] = "입력 공유: 상대 화면 정보 대기 중",
                ["input.controllingPeer"] = "입력 공유: 상대 제어 중 ({0})",
                ["input.receiving"] = "입력 공유: 입력 수신 중",
                ["input.ready"] = "입력 공유: 준비됨",
                ["settings.title"] = "클립보드 동기화 설정",
                ["settings.mode"] = "모드",
                ["settings.host"] = "호스트",
                ["settings.port"] = "포트",
                ["settings.password"] = "암호",
                ["settings.input"] = "입력",
                ["settings.scroll"] = "스크롤",
                ["settings.modifierKeys"] = "키",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "클라이언트",
                ["settings.server"] = "서버",
                ["settings.enableInputSharing"] = "입력 공유 활성화",
                ["settings.reverseVerticalScroll"] = "세로 스크롤 반전",
                ["settings.save"] = "저장",
                ["settings.cancel"] = "취소",
                ["settings.hostClientHint"] = "서버에 표시된 LAN IP를 입력하세요.",
                ["settings.hostServerHint"] = "같은 LAN의 클라이언트와 이 주소를 공유하세요.",
                ["settings.validationHost"] = "클라이언트 모드의 서버 LAN IP를 입력하세요.",
                ["settings.validationLoopback"] = "127.0.0.1이 아닌 서버의 LAN IP를 사용하세요.",
                ["settings.validationPassword"] = "모든 장치에 동일한 동기화 암호를 입력하세요.",
                ["layout.title"] = "화면 레이아웃",
                ["layout.subtitle"] = "기기들의 실제 배치에 맞게 각 화면을 드래그하세요.",
                ["layout.done"] = "완료",
                ["layout.disconnected"] = "연결 끊김",
                ["layout.inputDisabled"] = "입력 공유 꺼짐",
                ["layout.forgetDevice"] = "이 기기 잊기",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "자동 업데이트가 아직 구성되지 않았습니다. 릴리스 전에 NetSparkle Ed25519 키 쌍을 생성하고 Windows 업데이트 공개 키를 교체하세요.",
                ["status.betaExpired"] = "베타 종료, 업데이트 필요",
                ["beta.expiredTitle"] = "베타 기간 종료",
                ["beta.expiredMessage"] = "이 베타 빌드의 30일 체험 기간이 종료되었습니다. 계속 사용하려면 업데이트를 확인하세요.",
                ["beta.checkNowQuestion"] = "지금 업데이트를 확인하시겠습니까?"
            },
            [Language.Japanese] = new Dictionary<string, string>
            {
                ["app.name"] = "クリップボード同期",
                ["state.enabled"] = "有効",
                ["state.disabled"] = "無効",
                ["state.unknown"] = "不明",
                ["device.unknown"] = "不明なデバイス",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "状態: {0}",
                ["status.stopped"] = "停止中",
                ["status.copyFilesFirst"] = "先にファイルをコピーしてください",
                ["status.fileTransferStarted"] = "ファイル転送を開始しました",
                ["status.filesReceived"] = "ファイルを受信しました",
                ["status.setSyncPassword"] = "同期パスワードを設定してください",
                ["status.setServerLanIp"] = "サーバーの LAN IP を設定してください",
                ["status.useLanIp"] = "127.0.0.1 ではなく LAN IP を使用してください",
                ["status.encryptionFailed"] = "暗号化に失敗しました",
                ["status.clipboardPayloadTooLarge"] = "クリップボード内容が大きすぎます",
                ["status.inputPayloadTooLarge"] = "入力データが大きすぎます",
                ["status.restoreHistoryFailed"] = "履歴項目の復元に失敗しました",
                ["status.folderUnsupported"] = "フォルダのクリップボードは未対応です",
                ["status.fileTooLarge"] = "10 MB を超えるファイルをスキップしました",
                ["status.fileReadFailed"] = "ファイルクリップボードの読み取りに失敗しました",
                ["status.imageTooLarge"] = "10 MB を超える画像をスキップしました",
                ["status.sendFailed"] = "送信に失敗しました",
                ["status.connecting"] = "{0}:{1} に接続中",
                ["status.connected"] = "{0}:{1} に接続済み",
                ["status.disconnectedRetrying"] = "切断されました。再試行中",
                ["status.messageHandlerFailed"] = "メッセージ処理に失敗しました",
                ["status.serverPeers"] = "サーバー {0}、相手 {1} 台",
                ["status.serverError"] = "サーバーエラー: {0}",
                ["status.serverAcceptFailed"] = "サーバーの接続受付に失敗しました",
                ["menu.clipboardHistory"] = "クリップボード履歴",
                ["menu.noClipboardHistory"] = "クリップボード履歴はありません",
                ["menu.clearClipboardHistory"] = "クリップボード履歴を消去",
                ["menu.sendFiles"] = "クリップボードからファイルを送信",
                ["menu.enableInputSharing"] = "入力共有を有効化",
                ["menu.controlDevice"] = "制御デバイス",
                ["menu.controlDeviceWithTitle"] = "制御デバイス: {0}",
                ["menu.screenLayout"] = "画面レイアウト...",
                ["menu.clientMode"] = "クライアントモード",
                ["menu.serverMode"] = "サーバーモード",
                ["menu.configure"] = "設定...",
                ["menu.checkForUpdates"] = "アップデートを確認...",
                ["menu.about"] = "クリップボード同期について...",
                ["menu.homepage"] = "プロジェクトのホームページ",
                ["menu.start"] = "開始",
                ["menu.restart"] = "再起動",
                ["menu.stop"] = "停止",
                ["menu.launchAtLogin"] = "ログイン時に自動起動",
                ["menu.exit"] = "終了",
                ["about.title"] = "{0}について",
                ["about.message"] = "{0}\nバージョン {1}",
                ["edge.left"] = "左",
                ["edge.right"] = "右",
                ["edge.top"] = "上",
                ["edge.bottom"] = "下",
                ["history.text"] = "テキスト",
                ["history.textWithPreview"] = "テキスト: {0}",
                ["history.image"] = "画像: {0}",
                ["history.files"] = "ファイル: {0}{1}",
                ["input.off"] = "入力共有: オフ",
                ["input.waitingPeer"] = "入力共有: 相手を待機中",
                ["input.peerDisabled"] = "入力共有: 相手が無効です",
                ["input.waitingPeerScreen"] = "入力共有: 相手の画面情報を待機中",
                ["input.controllingPeer"] = "入力共有: 相手を制御中 ({0})",
                ["input.receiving"] = "入力共有: 入力を受信中",
                ["input.ready"] = "入力共有: 準備完了",
                ["settings.title"] = "クリップボード同期設定",
                ["settings.mode"] = "モード",
                ["settings.host"] = "ホスト",
                ["settings.port"] = "ポート",
                ["settings.password"] = "パスワード",
                ["settings.input"] = "入力",
                ["settings.scroll"] = "スクロール",
                ["settings.modifierKeys"] = "キー",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "クライアント",
                ["settings.server"] = "サーバー",
                ["settings.enableInputSharing"] = "入力共有を有効化",
                ["settings.reverseVerticalScroll"] = "垂直スクロールを反転",
                ["settings.save"] = "保存",
                ["settings.cancel"] = "キャンセル",
                ["settings.hostClientHint"] = "サーバーに表示された LAN IP を入力してください。",
                ["settings.hostServerHint"] = "同じ LAN のクライアントにこのアドレスを共有してください。",
                ["settings.validationHost"] = "クライアントモードのサーバー LAN IP を入力してください。",
                ["settings.validationLoopback"] = "127.0.0.1 ではなくサーバーの LAN IP を使用してください。",
                ["settings.validationPassword"] = "すべてのデバイスで同じ同期パスワードを入力してください。",
                ["layout.title"] = "画面レイアウト",
                ["layout.subtitle"] = "実際の配置に合わせて各画面をドラッグしてください。",
                ["layout.done"] = "完了",
                ["layout.disconnected"] = "切断済み",
                ["layout.inputDisabled"] = "入力共有オフ",
                ["layout.forgetDevice"] = "このデバイスを削除",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "自動更新はまだ設定されていません。リリース前に NetSparkle Ed25519 キーペアを生成し、Windows アップデーターの公開鍵を置き換えてください。",
                ["status.betaExpired"] = "ベータ終了、更新が必要です",
                ["beta.expiredTitle"] = "ベータ期間終了",
                ["beta.expiredMessage"] = "このベータビルドの30日間の試用期間が終了しました。引き続きご利用いただくにはアップデートを確認してください。",
                ["beta.checkNowQuestion"] = "今すぐアップデートを確認しますか？"
            }
        };

    public static string Text(string key)
    {
        if (Values.TryGetValue(CurrentLanguage, out var localized) && localized.TryGetValue(key, out var value))
        {
            return value;
        }
        return Values[Language.English].TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(string key, params object?[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Text(key), args);
    }

    public static string EdgeTitle(ScreenEdge edge)
    {
        return Text(edge switch
        {
            ScreenEdge.Left => "edge.left",
            ScreenEdge.Top => "edge.top",
            ScreenEdge.Bottom => "edge.bottom",
            _ => "edge.right"
        });
    }

    public static string ModifierTitle(KeyboardModifier modifier)
    {
        return Text(modifier switch
        {
            KeyboardModifier.Control => "modifier.control",
            KeyboardModifier.Alt => "modifier.alt",
            KeyboardModifier.Meta => "modifier.meta",
            _ => "modifier.shift"
        });
    }

    private static Language ResolveLanguage()
    {
        var name = CultureInfo.CurrentUICulture.Name.ToLowerInvariant();
        if (name.StartsWith("zh", StringComparison.Ordinal))
        {
            return Language.Chinese;
        }
        if (name.StartsWith("ko", StringComparison.Ordinal))
        {
            return Language.Korean;
        }
        if (name.StartsWith("ja", StringComparison.Ordinal))
        {
            return Language.Japanese;
        }
        return Language.English;
    }
}
