using System;
using System.Collections.Generic;
using System.Globalization;

namespace ClipboardSyncWin;

internal static class AppText
{
    private enum Language
    {
        English,
        Chinese,
        Korean,
        Japanese
    }

    private static readonly Language CurrentLanguage = ResolveLanguage();

    private static readonly IReadOnlyDictionary<Language, IReadOnlyDictionary<string, string>> Values =
        new Dictionary<Language, IReadOnlyDictionary<string, string>>
        {
            [Language.English] = new Dictionary<string, string>
            {
                ["app.name"] = "Clipboard Sync",
                ["state.enabled"] = "Enabled",
                ["state.disabled"] = "Disabled",
                ["state.unknown"] = "Unknown",
                ["device.unknown"] = "Unknown Device",
                ["device.unknownWithSuffix"] = "Unknown Device · {0}",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "Status: {0}",
                ["status.stopped"] = "stopped",
                ["status.syncPaused"] = "sync paused",
                ["status.copyFilesFirst"] = "copy files first",
                ["status.fileTransferStarted"] = "file transfer started",
                ["status.fileSendProgress"] = "sending files to {0}… {1}%",
                ["status.fileReceiveProgress"] = "receiving files… {0}%",
                ["status.filesSent"] = "files sent to {0}",
                ["status.fileTransferFailed"] = "file transfer failed: {0}",
                ["status.fileTransferBusy"] = "a file transfer is already running",
                ["status.filesReceived"] = "files received",
                ["status.filesReceivedPasteHint"] = "Files received. Paste them where you need them.",
                ["status.setSyncPassword"] = "set sync password",
                ["status.setServerLanIp"] = "set server LAN IP",
                ["status.useLanIp"] = "use LAN IP, not 127.0.0.1",
                ["status.encryptionFailed"] = "encryption failed",
                ["status.clipboardPayloadTooLarge"] = "clipboard payload too large",
                ["status.inputPayloadTooLarge"] = "input payload too large",
                ["status.restoreHistoryFailed"] = "failed to restore history item",
                ["status.folderUnsupported"] = "folder clipboard is not supported",
                ["status.fileTooLarge"] = "file over 10 MB skipped",
                ["status.fileReadFailed"] = "file clipboard read failed",
                ["status.imageTooLarge"] = "image over 10 MB skipped",
                ["status.sendFailed"] = "send failed",
                ["status.connecting"] = "connecting {0}:{1}",
                ["status.connected"] = "connected {0}:{1}",
                ["status.disconnectedRetrying"] = "disconnected; retrying",
                ["status.messageHandlerFailed"] = "message handler failed",
                ["status.serverPeers"] = "server {0}, {1} peer(s)",
                ["status.serverError"] = "server error: {0}",
                ["status.serverAcceptFailed"] = "server accept failed",
                ["menu.clipboardHistory"] = "Clipboard History",
                ["menu.noClipboardHistory"] = "No clipboard history",
                ["menu.clearClipboardHistory"] = "Clear Clipboard History",
                ["menu.sendFiles"] = "Send Files from Clipboard",
                ["menu.sendFilesNoFile"] = "Send Files from Clipboard (no file copied)",
                ["menu.sendFilesWithName"] = "Send Files from Clipboard ({0})",
                ["menu.noPeers"] = "No Connected Devices",
                ["menu.enableInputSharing"] = "Enable Input Sharing",
                ["menu.controlDevice"] = "Control Device",
                ["menu.controlDeviceWithTitle"] = "Control Device: {0}",
                ["menu.screenLayout"] = "Screen Layout...",
                ["menu.portForward"] = "Port Forward...",
                ["menu.completeSetup"] = "Complete Setup...",
                ["menu.reconnect"] = "Reconnect",
                ["menu.moreFeatures"] = "More Features",
                ["forward.title"] = "Port Forward",
                ["forward.subtitle"] = "Forward a TCP port on one device to a port on another. Connections to In are tunneled over the encrypted sync connection and delivered to Out.",
                ["forward.in"] = "In (listen)",
                ["forward.out"] = "Out (destination)",
                ["forward.lan"] = "LAN",
                ["forward.note"] = "Note",
                ["forward.notePlaceholder"] = "Optional note",
                ["forward.lanTooltip"] = "Off: listen on 127.0.0.1 only (this machine). On: listen on 0.0.0.0 so other machines on the LAN can reach this port.",
                ["forward.hostTooltip"] = "Address the Out device connects to. Default 127.0.0.1 (a service on the Out device itself); change it to reach another host the Out device can see.",
                ["forward.status"] = "",
                ["forward.enabled"] = "On",
                ["forward.enabledTooltip"] = "Enable or disable this forward. Changes apply when you save.",
                ["forward.toggleOn"] = "On",
                ["forward.toggleOff"] = "Off",
                ["forward.reasonPrivileged"] = "needs a port >= 1024 (admin required)",
                ["forward.offlineDevice"] = "Offline Device",
                ["forward.statusListening"] = "listening on port {0}",
                ["forward.statusFailed"] = "port listening failed: {0}",
                ["forward.statusDisabled"] = "disabled",
                ["forward.statusOffline"] = "In device offline",
                ["forward.statusOutOffline"] = "Out device offline",
                ["forward.statusStarting"] = "starting...",
                ["forward.add"] = "Add Forward",
                ["forward.empty"] = "No port forwards yet. Click Add Forward to create one.",
                ["forward.validationPort"] = "Ports must be numbers from 1 to 65535.",
                ["forward.validationSame"] = "In and Out cannot be the same port on the same device.",
                ["forward.validationDuplicate"] = "Two rules listen on the same port of the same device.",
                ["forward.remoteConflict"] = "Rules changed on another device. Your draft is preserved; close and reopen this window to load the remote changes.",
                ["status.forwardListenFailed"] = "port forward {0} failed: {1}",
                ["status.forwardListenPermission"] = "port forward {0} denied - use a port >= 1024 (privileged ports need admin)",
                ["menu.configure"] = "Settings...",
                ["menu.checkForUpdates"] = "Check for Updates...",
                ["menu.about"] = "About Clipboard Sync...",
                ["menu.homepage"] = "Project Homepage",
                ["menu.pauseSync"] = "Pause Sync",
                ["menu.resumeSync"] = "Resume Sync",
                ["menu.launchAtLogin"] = "Launch at Login",
                ["menu.exit"] = "Exit",
                ["about.title"] = "About {0}",
                ["about.message"] = "{0}\nVersion {1}",
                ["edge.left"] = "Left",
                ["edge.right"] = "Right",
                ["edge.top"] = "Top",
                ["edge.bottom"] = "Bottom",
                ["history.text"] = "Text",
                ["history.textWithPreview"] = "Text: {0}",
                ["history.image"] = "Image: {0}",
                ["history.files"] = "Files: {0}{1}",
                ["input.off"] = "Input Sharing: off",
                ["input.waitingPeer"] = "Input Sharing: waiting for peer",
                ["input.peerDisabled"] = "Input Sharing: peer disabled",
                ["input.waitingPeerScreen"] = "Input Sharing: waiting for peer screen",
                ["input.controllingPeer"] = "Input Sharing: controlling peer ({0})",
                ["input.receiving"] = "Input Sharing: receiving input",
                ["input.ready"] = "Input Sharing: ready",
                ["settings.title"] = "Clipboard Sync Settings",
                ["settings.firstRunHeader"] = "Connect your devices",
                ["settings.firstRunSubtitle"] = "Set one device as the server, then configure the others as child devices using the same address and password.",
                ["settings.sectionConnection"] = "Connection",
                ["settings.sectionInput"] = "Input Sharing",
                ["settings.mode"] = "Mode",
                ["settings.host"] = "Host",
                ["settings.port"] = "Port",
                ["settings.password"] = "Password",
                ["settings.encryption"] = "Security",
                ["settings.encryptTransport"] = "Encrypt transport (uncheck on trusted networks to save CPU)",
                ["settings.input"] = "Input",
                ["settings.scroll"] = "Scroll",
                ["settings.modifierKeys"] = "Receive Key Mapping",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "Child Device",
                ["settings.server"] = "Server",
                ["settings.enableInputSharing"] = "Enable Input Sharing",
                ["settings.reverseVerticalScroll"] = "Reverse Vertical Scroll",
                ["settings.save"] = "Save",
                ["settings.cancel"] = "Cancel",
                ["settings.hostClientHint"] = "Enter the LAN IP shown on the server.",
                ["settings.hostServerHint"] = "Share this address with clients on the same LAN.",
                ["settings.copyAddress"] = "Copy Address",
                ["settings.copyPassword"] = "Copy Password",
                ["settings.validationHost"] = "Enter the server LAN address for this child device.",
                ["settings.validationLoopback"] = "Use the server machine's LAN IP, not 127.0.0.1.",
                ["settings.validationPassword"] = "Enter the same sync password on every device.",
                ["settings.confirmNoEncryption"] = "Clipboard and input data will travel unencrypted, authenticated by the sync password. Only do this on a trusted network. Continue?",
                ["layout.title"] = "Screen Layout",
                ["layout.subtitle"] = "Drag screens to match your desk. Right-click an offline device to forget it.",
                ["layout.done"] = "Done",
                ["layout.disconnected"] = "Disconnected",
                ["layout.inputDisabled"] = "Input Sharing Off",
                ["layout.thisDevice"] = "This Device",
                ["layout.autoArrange"] = "Auto Arrange",
                ["layout.saved"] = "Layout saved",
                ["layout.forgetDevice"] = "Forget This Device",
                ["layout.forgetConfirm"] = "Forget this offline device and remove its saved screens?",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "Auto-update is not configured yet. Generate a NetSparkle Ed25519 keypair and replace the Windows updater public key before release.",
                ["status.betaExpired"] = "beta ended, update required",
                ["beta.expiredTitle"] = "Beta Period Ended",
                ["beta.expiredMessage"] = "This beta build's 30-day trial has ended. Please check for updates to keep using Clipboard Sync.",
                ["beta.checkNowQuestion"] = "Check for updates now?"
            },
            [Language.Chinese] = new Dictionary<string, string>
            {
                ["app.name"] = "剪贴板同步",
                ["state.enabled"] = "已启用",
                ["state.disabled"] = "已禁用",
                ["state.unknown"] = "未知",
                ["device.unknown"] = "未知设备",
                ["device.unknownWithSuffix"] = "未知设备 · {0}",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "状态：{0}",
                ["status.stopped"] = "已停止",
                ["status.syncPaused"] = "同步已暂停",
                ["status.copyFilesFirst"] = "请先复制文件",
                ["status.fileTransferStarted"] = "文件传输已开始",
                ["status.fileSendProgress"] = "正在发送文件到 {0}… {1}%",
                ["status.fileReceiveProgress"] = "正在接收文件… {0}%",
                ["status.filesSent"] = "文件已发送到 {0}",
                ["status.fileTransferFailed"] = "文件传输失败：{0}",
                ["status.fileTransferBusy"] = "已有文件传输正在进行",
                ["status.filesReceived"] = "已收到文件",
                ["status.filesReceivedPasteHint"] = "已收到文件，你可以在需要的位置粘贴。",
                ["status.setSyncPassword"] = "请设置同步密码",
                ["status.setServerLanIp"] = "请设置服务器局域网 IP",
                ["status.useLanIp"] = "请使用局域网 IP，不要用 127.0.0.1",
                ["status.encryptionFailed"] = "加密失败",
                ["status.clipboardPayloadTooLarge"] = "剪贴板内容过大",
                ["status.inputPayloadTooLarge"] = "输入数据过大",
                ["status.restoreHistoryFailed"] = "恢复历史记录失败",
                ["status.folderUnsupported"] = "不支持文件夹剪贴板",
                ["status.fileTooLarge"] = "文件超过 10 MB，已跳过",
                ["status.fileReadFailed"] = "读取文件剪贴板失败",
                ["status.imageTooLarge"] = "图片超过 10 MB，已跳过",
                ["status.sendFailed"] = "发送失败",
                ["status.connecting"] = "正在连接 {0}:{1}",
                ["status.connected"] = "已连接 {0}:{1}",
                ["status.disconnectedRetrying"] = "已断开，正在重试",
                ["status.messageHandlerFailed"] = "消息处理失败",
                ["status.serverPeers"] = "服务器 {0}，{1} 个对端",
                ["status.serverError"] = "服务器错误：{0}",
                ["status.serverAcceptFailed"] = "服务器接受连接失败",
                ["menu.clipboardHistory"] = "剪贴板历史",
                ["menu.noClipboardHistory"] = "无剪贴板历史",
                ["menu.clearClipboardHistory"] = "清除剪贴板历史",
                ["menu.sendFiles"] = "从剪贴板发送文件",
                ["menu.sendFilesNoFile"] = "从剪贴板发送文件（未复制文件）",
                ["menu.sendFilesWithName"] = "从剪贴板发送文件（{0}）",
                ["menu.noPeers"] = "无已连接设备",
                ["menu.enableInputSharing"] = "启用输入共享",
                ["menu.controlDevice"] = "控制设备",
                ["menu.controlDeviceWithTitle"] = "控制设备：{0}",
                ["menu.screenLayout"] = "屏幕布局...",
                ["menu.portForward"] = "端口转发...",
                ["menu.completeSetup"] = "完成设置...",
                ["menu.reconnect"] = "重新连接",
                ["menu.moreFeatures"] = "更多功能",
                ["forward.title"] = "端口转发",
                ["forward.subtitle"] = "将一台设备的 TCP 端口转发到另一台设备的端口。连接到“入口”的流量会经加密同步连接隧道送达“出口”。",
                ["forward.in"] = "入口（监听）",
                ["forward.out"] = "出口（目标）",
                ["forward.lan"] = "局域网",
                ["forward.note"] = "备注",
                ["forward.notePlaceholder"] = "备注（可选）",
                ["forward.lanTooltip"] = "关闭：仅监听 127.0.0.1（本机）。开启：监听 0.0.0.0，局域网内其他机器也能访问此端口。",
                ["forward.hostTooltip"] = "出口设备连接的地址。默认 127.0.0.1（出口设备自身的服务）；可改为出口设备能访问的其他主机。",
                ["forward.status"] = "",
                ["forward.enabled"] = "启用",
                ["forward.enabledTooltip"] = "启用或禁用此转发，保存后生效。",
                ["forward.toggleOn"] = "开",
                ["forward.toggleOff"] = "关",
                ["forward.reasonPrivileged"] = "需要 >= 1024 的端口（否则需要管理员权限）",
                ["forward.offlineDevice"] = "离线设备",
                ["forward.statusListening"] = "正在监听端口 {0}",
                ["forward.statusFailed"] = "端口监听失败：{0}",
                ["forward.statusDisabled"] = "已禁用",
                ["forward.statusOffline"] = "入口设备离线",
                ["forward.statusOutOffline"] = "出口设备离线",
                ["forward.statusStarting"] = "正在启动…",
                ["forward.add"] = "添加转发",
                ["forward.empty"] = "暂无端口转发。点击“添加转发”创建。",
                ["forward.validationPort"] = "端口必须是 1 到 65535 之间的数字。",
                ["forward.validationSame"] = "入口和出口不能是同一设备上的同一端口。",
                ["forward.validationDuplicate"] = "同一设备上的同一端口被多条规则监听。",
                ["forward.remoteConflict"] = "规则已在另一台设备上更改。你的草稿已保留；关闭并重新打开此窗口可载入远端更改。",
                ["status.forwardListenFailed"] = "端口转发 {0} 失败：{1}",
                ["status.forwardListenPermission"] = "端口转发 {0} 被拒绝 - 请使用 >= 1024 的端口（特权端口需要管理员权限）",
                ["menu.configure"] = "设置...",
                ["menu.checkForUpdates"] = "检查更新...",
                ["menu.about"] = "关于剪贴板同步...",
                ["menu.homepage"] = "项目主页",
                ["menu.pauseSync"] = "暂停同步",
                ["menu.resumeSync"] = "恢复同步",
                ["menu.launchAtLogin"] = "登录时自动启动",
                ["menu.exit"] = "退出",
                ["about.title"] = "关于{0}",
                ["about.message"] = "{0}\n版本 {1}",
                ["edge.left"] = "左侧",
                ["edge.right"] = "右侧",
                ["edge.top"] = "上方",
                ["edge.bottom"] = "下方",
                ["history.text"] = "文本",
                ["history.textWithPreview"] = "文本：{0}",
                ["history.image"] = "图片：{0}",
                ["history.files"] = "文件：{0}{1}",
                ["input.off"] = "输入共享：关闭",
                ["input.waitingPeer"] = "输入共享：等待对端",
                ["input.peerDisabled"] = "输入共享：对端已禁用",
                ["input.waitingPeerScreen"] = "输入共享：等待对端屏幕信息",
                ["input.controllingPeer"] = "输入共享：正在控制对端（{0}）",
                ["input.receiving"] = "输入共享：正在接收输入",
                ["input.ready"] = "输入共享：就绪",
                ["settings.title"] = "剪贴板同步设置",
                ["settings.firstRunHeader"] = "连接你的设备",
                ["settings.firstRunSubtitle"] = "先将一台设备设为服务端，再让其它设备使用相同的地址和密码作为子设备连接。",
                ["settings.sectionConnection"] = "连接",
                ["settings.sectionInput"] = "输入共享",
                ["settings.mode"] = "模式",
                ["settings.host"] = "主机",
                ["settings.port"] = "端口",
                ["settings.password"] = "密码",
                ["settings.encryption"] = "安全",
                ["settings.encryptTransport"] = "加密传输（可信网络可取消勾选以降低 CPU 占用）",
                ["settings.input"] = "输入",
                ["settings.scroll"] = "滚动",
                ["settings.modifierKeys"] = "接收按键映射",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "子设备",
                ["settings.server"] = "服务端",
                ["settings.enableInputSharing"] = "启用输入共享",
                ["settings.reverseVerticalScroll"] = "反转垂直滚动",
                ["settings.save"] = "保存",
                ["settings.cancel"] = "取消",
                ["settings.hostClientHint"] = "输入服务器显示的局域网 IP。",
                ["settings.hostServerHint"] = "将此地址分享给同一局域网内的客户端。",
                ["settings.copyAddress"] = "复制地址",
                ["settings.copyPassword"] = "复制密码",
                ["settings.validationHost"] = "请输入这台子设备要连接的服务端局域网地址。",
                ["settings.validationLoopback"] = "请使用服务器的局域网 IP，不要用 127.0.0.1。",
                ["settings.validationPassword"] = "请在每台设备上输入相同的同步密码。",
                ["settings.confirmNoEncryption"] = "剪贴板与输入数据将不加密传输，仅使用同步密码进行认证。请仅在可信网络中使用。是否继续？",
                ["layout.title"] = "屏幕布局",
                ["layout.subtitle"] = "拖动屏幕以匹配桌面摆放；右键离线设备可将其忘记。",
                ["layout.done"] = "完成",
                ["layout.disconnected"] = "已断开",
                ["layout.inputDisabled"] = "输入共享已关闭",
                ["layout.thisDevice"] = "本机",
                ["layout.autoArrange"] = "自动排列",
                ["layout.saved"] = "布局已保存",
                ["layout.forgetDevice"] = "忘记此设备",
                ["layout.forgetConfirm"] = "忘记这台离线设备并移除其已保存的屏幕吗？",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "尚未配置自动更新。发布前请生成 NetSparkle Ed25519 密钥对，并替换 Windows 更新器公钥。",
                ["status.betaExpired"] = "测试已结束，需要更新",
                ["beta.expiredTitle"] = "测试期已结束",
                ["beta.expiredMessage"] = "此测试版本的 30 天试用期已结束，请检查更新以继续使用剪贴板同步。",
                ["beta.checkNowQuestion"] = "现在检查更新吗？"
            },
            [Language.Korean] = new Dictionary<string, string>
            {
                ["app.name"] = "클립보드 동기화",
                ["state.enabled"] = "활성",
                ["state.disabled"] = "비활성",
                ["state.unknown"] = "알 수 없음",
                ["device.unknown"] = "알 수 없는 장치",
                ["device.unknownWithSuffix"] = "알 수 없는 장치 · {0}",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "상태: {0}",
                ["status.stopped"] = "중지됨",
                ["status.syncPaused"] = "동기화 일시 정지됨",
                ["status.copyFilesFirst"] = "먼저 파일을 복사하세요",
                ["status.fileTransferStarted"] = "파일 전송 시작됨",
                ["status.fileSendProgress"] = "{0}(으)로 파일 전송 중… {1}%",
                ["status.fileReceiveProgress"] = "파일 수신 중… {0}%",
                ["status.filesSent"] = "{0}(으)로 파일을 보냈습니다",
                ["status.fileTransferFailed"] = "파일 전송 실패: {0}",
                ["status.fileTransferBusy"] = "이미 파일 전송이 진행 중입니다",
                ["status.filesReceived"] = "파일을 받았습니다",
                ["status.filesReceivedPasteHint"] = "파일을 받았습니다. 필요한 위치에 붙여넣을 수 있습니다.",
                ["status.setSyncPassword"] = "동기화 암호를 설정하세요",
                ["status.setServerLanIp"] = "서버 LAN IP를 설정하세요",
                ["status.useLanIp"] = "127.0.0.1 대신 LAN IP를 사용하세요",
                ["status.encryptionFailed"] = "암호화 실패",
                ["status.clipboardPayloadTooLarge"] = "클립보드 데이터가 너무 큼",
                ["status.inputPayloadTooLarge"] = "입력 데이터가 너무 큼",
                ["status.restoreHistoryFailed"] = "기록 항목 복원 실패",
                ["status.folderUnsupported"] = "폴더 클립보드는 지원되지 않음",
                ["status.fileTooLarge"] = "10 MB 초과 파일 건너뜀",
                ["status.fileReadFailed"] = "파일 클립보드 읽기 실패",
                ["status.imageTooLarge"] = "10 MB 초과 이미지 건너뜀",
                ["status.sendFailed"] = "전송 실패",
                ["status.connecting"] = "{0}:{1} 연결 중",
                ["status.connected"] = "{0}:{1} 연결됨",
                ["status.disconnectedRetrying"] = "연결 끊김; 다시 시도 중",
                ["status.messageHandlerFailed"] = "메시지 처리 실패",
                ["status.serverPeers"] = "서버 {0}, 상대 {1}개",
                ["status.serverError"] = "서버 오류: {0}",
                ["status.serverAcceptFailed"] = "서버 연결 수락 실패",
                ["menu.clipboardHistory"] = "클립보드 기록",
                ["menu.noClipboardHistory"] = "클립보드 기록 없음",
                ["menu.clearClipboardHistory"] = "클립보드 기록 지우기",
                ["menu.sendFiles"] = "클립보드에서 파일 보내기",
                ["menu.sendFilesNoFile"] = "클립보드에서 파일 보내기 (복사된 파일 없음)",
                ["menu.sendFilesWithName"] = "클립보드에서 파일 보내기 ({0})",
                ["menu.noPeers"] = "연결된 기기 없음",
                ["menu.enableInputSharing"] = "입력 공유 활성화",
                ["menu.controlDevice"] = "제어 장치",
                ["menu.controlDeviceWithTitle"] = "제어 장치: {0}",
                ["menu.screenLayout"] = "화면 레이아웃...",
                ["menu.portForward"] = "포트 포워딩...",
                ["menu.completeSetup"] = "설정 완료...",
                ["menu.reconnect"] = "다시 연결",
                ["menu.moreFeatures"] = "더 많은 기능",
                ["forward.title"] = "포트 포워딩",
                ["forward.subtitle"] = "한 기기의 TCP 포트를 다른 기기의 포트로 전달합니다. In으로 들어온 연결은 암호화된 동기화 연결을 통해 Out으로 전달됩니다.",
                ["forward.in"] = "In (수신)",
                ["forward.out"] = "Out (대상)",
                ["forward.lan"] = "LAN",
                ["forward.note"] = "메모",
                ["forward.notePlaceholder"] = "메모 (선택)",
                ["forward.lanTooltip"] = "끄면 127.0.0.1(이 기기)에서만 수신합니다. 켜면 0.0.0.0에서 수신하여 LAN의 다른 기기도 이 포트에 접근할 수 있습니다.",
                ["forward.hostTooltip"] = "Out 기기가 연결하는 주소. 기본값 127.0.0.1(Out 기기 자체의 서비스); Out 기기가 접근 가능한 다른 호스트로 변경할 수 있습니다.",
                ["forward.status"] = "",
                ["forward.enabled"] = "사용",
                ["forward.enabledTooltip"] = "이 포워딩을 사용/해제합니다. 저장하면 적용됩니다.",
                ["forward.toggleOn"] = "켜짐",
                ["forward.toggleOff"] = "꺼짐",
                ["forward.reasonPrivileged"] = "1024 이상 포트가 필요합니다(특권 포트는 관리자 권한 필요)",
                ["forward.offlineDevice"] = "오프라인 기기",
                ["forward.statusListening"] = "포트 {0} 수신 중",
                ["forward.statusFailed"] = "포트 수신 실패: {0}",
                ["forward.statusDisabled"] = "사용 안 함",
                ["forward.statusOffline"] = "In 기기 오프라인",
                ["forward.statusOutOffline"] = "Out 기기 오프라인",
                ["forward.statusStarting"] = "시작 중…",
                ["forward.add"] = "포워딩 추가",
                ["forward.empty"] = "포트 포워딩이 없습니다. 포워딩 추가를 눌러 만드세요.",
                ["forward.validationPort"] = "포트는 1에서 65535 사이의 숫자여야 합니다.",
                ["forward.validationSame"] = "In과 Out은 같은 기기의 같은 포트일 수 없습니다.",
                ["forward.validationDuplicate"] = "같은 기기의 같은 포트를 여러 규칙이 수신합니다.",
                ["forward.remoteConflict"] = "다른 기기에서 규칙이 변경되었습니다. 현재 초안은 유지됩니다. 창을 닫았다가 다시 열어 원격 변경 사항을 불러오세요.",
                ["status.forwardListenFailed"] = "포트 포워딩 {0} 실패: {1}",
                ["status.forwardListenPermission"] = "포트 포워딩 {0} 거부됨 - 1024 이상 포트를 사용하세요(특권 포트는 관리자 권한 필요)",
                ["menu.configure"] = "설정...",
                ["menu.checkForUpdates"] = "업데이트 확인...",
                ["menu.about"] = "클립보드 동기화 정보...",
                ["menu.homepage"] = "프로젝트 홈페이지",
                ["menu.pauseSync"] = "동기화 일시 정지",
                ["menu.resumeSync"] = "동기화 재개",
                ["menu.launchAtLogin"] = "로그인 시 자동 실행",
                ["menu.exit"] = "종료",
                ["about.title"] = "{0} 정보",
                ["about.message"] = "{0}\n버전 {1}",
                ["edge.left"] = "왼쪽",
                ["edge.right"] = "오른쪽",
                ["edge.top"] = "위",
                ["edge.bottom"] = "아래",
                ["history.text"] = "텍스트",
                ["history.textWithPreview"] = "텍스트: {0}",
                ["history.image"] = "이미지: {0}",
                ["history.files"] = "파일: {0}{1}",
                ["input.off"] = "입력 공유: 꺼짐",
                ["input.waitingPeer"] = "입력 공유: 상대 대기 중",
                ["input.peerDisabled"] = "입력 공유: 상대가 비활성화됨",
                ["input.waitingPeerScreen"] = "입력 공유: 상대 화면 정보 대기 중",
                ["input.controllingPeer"] = "입력 공유: 상대 제어 중 ({0})",
                ["input.receiving"] = "입력 공유: 입력 수신 중",
                ["input.ready"] = "입력 공유: 준비됨",
                ["settings.title"] = "클립보드 동기화 설정",
                ["settings.firstRunHeader"] = "기기 연결",
                ["settings.firstRunSubtitle"] = "한 기기를 서버로 설정한 다음, 다른 기기를 같은 주소와 암호를 사용하는 하위 기기로 설정하세요.",
                ["settings.sectionConnection"] = "연결",
                ["settings.sectionInput"] = "입력 공유",
                ["settings.mode"] = "모드",
                ["settings.host"] = "호스트",
                ["settings.port"] = "포트",
                ["settings.password"] = "암호",
                ["settings.encryption"] = "보안",
                ["settings.encryptTransport"] = "전송 암호화 (신뢰할 수 있는 네트워크에서는 해제해 CPU 절약)",
                ["settings.input"] = "입력",
                ["settings.scroll"] = "스크롤",
                ["settings.modifierKeys"] = "수신 키 매핑",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "하위 기기",
                ["settings.server"] = "서버",
                ["settings.enableInputSharing"] = "입력 공유 활성화",
                ["settings.reverseVerticalScroll"] = "세로 스크롤 반전",
                ["settings.save"] = "저장",
                ["settings.cancel"] = "취소",
                ["settings.hostClientHint"] = "서버에 표시된 LAN IP를 입력하세요.",
                ["settings.hostServerHint"] = "같은 LAN의 클라이언트와 이 주소를 공유하세요.",
                ["settings.copyAddress"] = "주소 복사",
                ["settings.copyPassword"] = "암호 복사",
                ["settings.validationHost"] = "이 하위 기기가 연결할 서버 LAN 주소를 입력하세요.",
                ["settings.validationLoopback"] = "127.0.0.1이 아닌 서버의 LAN IP를 사용하세요.",
                ["settings.validationPassword"] = "모든 장치에 동일한 동기화 암호를 입력하세요.",
                ["settings.confirmNoEncryption"] = "클립보드와 입력 데이터가 암호화되지 않은 채 전송되며 동기화 암호로만 인증됩니다. 신뢰할 수 있는 네트워크에서만 사용하세요. 계속할까요?",
                ["layout.title"] = "화면 레이아웃",
                ["layout.subtitle"] = "기기들의 실제 배치에 맞게 각 화면을 드래그하세요.",
                ["layout.done"] = "완료",
                ["layout.disconnected"] = "연결 끊김",
                ["layout.inputDisabled"] = "입력 공유 꺼짐",
                ["layout.thisDevice"] = "이 기기",
                ["layout.autoArrange"] = "자동 정렬",
                ["layout.saved"] = "레이아웃 저장됨",
                ["layout.forgetDevice"] = "이 기기 잊기",
                ["layout.forgetConfirm"] = "이 오프라인 기기와 저장된 화면을 지울까요?",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "자동 업데이트가 아직 구성되지 않았습니다. 릴리스 전에 NetSparkle Ed25519 키 쌍을 생성하고 Windows 업데이트 공개 키를 교체하세요.",
                ["status.betaExpired"] = "베타 종료, 업데이트 필요",
                ["beta.expiredTitle"] = "베타 기간 종료",
                ["beta.expiredMessage"] = "이 베타 빌드의 30일 체험 기간이 종료되었습니다. 계속 사용하려면 업데이트를 확인하세요.",
                ["beta.checkNowQuestion"] = "지금 업데이트를 확인하시겠습니까?"
            },
            [Language.Japanese] = new Dictionary<string, string>
            {
                ["app.name"] = "クリップボード同期",
                ["state.enabled"] = "有効",
                ["state.disabled"] = "無効",
                ["state.unknown"] = "不明",
                ["device.unknown"] = "不明なデバイス",
                ["device.unknownWithSuffix"] = "不明なデバイス · {0}",
                ["device.titleStatus"] = "{0} [{1}]",
                ["status.prefix"] = "状態: {0}",
                ["status.stopped"] = "停止中",
                ["status.syncPaused"] = "同期は一時停止中",
                ["status.copyFilesFirst"] = "先にファイルをコピーしてください",
                ["status.fileTransferStarted"] = "ファイル転送を開始しました",
                ["status.fileSendProgress"] = "{0} へファイル送信中… {1}%",
                ["status.fileReceiveProgress"] = "ファイル受信中… {0}%",
                ["status.filesSent"] = "{0} へファイルを送信しました",
                ["status.fileTransferFailed"] = "ファイル転送に失敗しました: {0}",
                ["status.fileTransferBusy"] = "ファイル転送は既に実行中です",
                ["status.filesReceived"] = "ファイルを受信しました",
                ["status.filesReceivedPasteHint"] = "ファイルを受信しました。必要な場所に貼り付けできます。",
                ["status.setSyncPassword"] = "同期パスワードを設定してください",
                ["status.setServerLanIp"] = "サーバーの LAN IP を設定してください",
                ["status.useLanIp"] = "127.0.0.1 ではなく LAN IP を使用してください",
                ["status.encryptionFailed"] = "暗号化に失敗しました",
                ["status.clipboardPayloadTooLarge"] = "クリップボード内容が大きすぎます",
                ["status.inputPayloadTooLarge"] = "入力データが大きすぎます",
                ["status.restoreHistoryFailed"] = "履歴項目の復元に失敗しました",
                ["status.folderUnsupported"] = "フォルダのクリップボードは未対応です",
                ["status.fileTooLarge"] = "10 MB を超えるファイルをスキップしました",
                ["status.fileReadFailed"] = "ファイルクリップボードの読み取りに失敗しました",
                ["status.imageTooLarge"] = "10 MB を超える画像をスキップしました",
                ["status.sendFailed"] = "送信に失敗しました",
                ["status.connecting"] = "{0}:{1} に接続中",
                ["status.connected"] = "{0}:{1} に接続済み",
                ["status.disconnectedRetrying"] = "切断されました。再試行中",
                ["status.messageHandlerFailed"] = "メッセージ処理に失敗しました",
                ["status.serverPeers"] = "サーバー {0}、相手 {1} 台",
                ["status.serverError"] = "サーバーエラー: {0}",
                ["status.serverAcceptFailed"] = "サーバーの接続受付に失敗しました",
                ["menu.clipboardHistory"] = "クリップボード履歴",
                ["menu.noClipboardHistory"] = "クリップボード履歴はありません",
                ["menu.clearClipboardHistory"] = "クリップボード履歴を消去",
                ["menu.sendFiles"] = "クリップボードからファイルを送信",
                ["menu.sendFilesNoFile"] = "クリップボードからファイルを送信（ファイル未コピー）",
                ["menu.sendFilesWithName"] = "クリップボードからファイルを送信（{0}）",
                ["menu.noPeers"] = "接続中のデバイスなし",
                ["menu.enableInputSharing"] = "入力共有を有効化",
                ["menu.controlDevice"] = "制御デバイス",
                ["menu.controlDeviceWithTitle"] = "制御デバイス: {0}",
                ["menu.screenLayout"] = "画面レイアウト...",
                ["menu.portForward"] = "ポート転送...",
                ["menu.completeSetup"] = "設定を完了...",
                ["menu.reconnect"] = "再接続",
                ["menu.moreFeatures"] = "その他の機能",
                ["forward.title"] = "ポート転送",
                ["forward.subtitle"] = "あるデバイスの TCP ポートを別のデバイスのポートへ転送します。In への接続は暗号化された同期接続を経由して Out に届きます。",
                ["forward.in"] = "In（待ち受け）",
                ["forward.out"] = "Out（宛先）",
                ["forward.lan"] = "LAN",
                ["forward.note"] = "メモ",
                ["forward.notePlaceholder"] = "メモ（任意）",
                ["forward.lanTooltip"] = "オフ: 127.0.0.1（このマシン）のみで待ち受けます。オン: 0.0.0.0 で待ち受け、LAN 上の他のマシンからもこのポートにアクセスできます。",
                ["forward.hostTooltip"] = "Out デバイスが接続する宛先アドレス。既定は 127.0.0.1（Out デバイス自身のサービス）。Out デバイスから到達できる別のホストに変更できます。",
                ["forward.status"] = "",
                ["forward.enabled"] = "有効",
                ["forward.enabledTooltip"] = "この転送を有効/無効にします。保存時に反映されます。",
                ["forward.toggleOn"] = "オン",
                ["forward.toggleOff"] = "オフ",
                ["forward.reasonPrivileged"] = "1024 以上のポートが必要です（特権ポートは管理者権限が必要）",
                ["forward.offlineDevice"] = "オフラインデバイス",
                ["forward.statusListening"] = "ポート {0} で待ち受け中",
                ["forward.statusFailed"] = "ポート待ち受け失敗: {0}",
                ["forward.statusDisabled"] = "無効",
                ["forward.statusOffline"] = "In デバイスがオフライン",
                ["forward.statusOutOffline"] = "Out デバイスがオフライン",
                ["forward.statusStarting"] = "開始中…",
                ["forward.add"] = "転送を追加",
                ["forward.empty"] = "ポート転送はまだありません。「転送を追加」で作成してください。",
                ["forward.validationPort"] = "ポートは 1 から 65535 の数字である必要があります。",
                ["forward.validationSame"] = "In と Out を同じデバイスの同じポートにはできません。",
                ["forward.validationDuplicate"] = "同じデバイスの同じポートを複数のルールが待ち受けています。",
                ["forward.remoteConflict"] = "別のデバイスでルールが変更されました。編集中の内容は保持されています。ウィンドウを閉じて再度開くとリモートの変更を読み込めます。",
                ["status.forwardListenFailed"] = "ポート転送 {0} が失敗しました: {1}",
                ["status.forwardListenPermission"] = "ポート転送 {0} は拒否されました - 1024 以上のポートを使用してください（特権ポートは管理者権限が必要）",
                ["menu.configure"] = "設定...",
                ["menu.checkForUpdates"] = "アップデートを確認...",
                ["menu.about"] = "クリップボード同期について...",
                ["menu.homepage"] = "プロジェクトのホームページ",
                ["menu.pauseSync"] = "同期を一時停止",
                ["menu.resumeSync"] = "同期を再開",
                ["menu.launchAtLogin"] = "ログイン時に自動起動",
                ["menu.exit"] = "終了",
                ["about.title"] = "{0}について",
                ["about.message"] = "{0}\nバージョン {1}",
                ["edge.left"] = "左",
                ["edge.right"] = "右",
                ["edge.top"] = "上",
                ["edge.bottom"] = "下",
                ["history.text"] = "テキスト",
                ["history.textWithPreview"] = "テキスト: {0}",
                ["history.image"] = "画像: {0}",
                ["history.files"] = "ファイル: {0}{1}",
                ["input.off"] = "入力共有: オフ",
                ["input.waitingPeer"] = "入力共有: 相手を待機中",
                ["input.peerDisabled"] = "入力共有: 相手が無効です",
                ["input.waitingPeerScreen"] = "入力共有: 相手の画面情報を待機中",
                ["input.controllingPeer"] = "入力共有: 相手を制御中 ({0})",
                ["input.receiving"] = "入力共有: 入力を受信中",
                ["input.ready"] = "入力共有: 準備完了",
                ["settings.title"] = "クリップボード同期設定",
                ["settings.firstRunHeader"] = "デバイスを接続",
                ["settings.firstRunSubtitle"] = "1 台をサーバーに設定し、ほかのデバイスを同じアドレスとパスワードを使う子デバイスとして設定します。",
                ["settings.sectionConnection"] = "接続",
                ["settings.sectionInput"] = "入力共有",
                ["settings.mode"] = "モード",
                ["settings.host"] = "ホスト",
                ["settings.port"] = "ポート",
                ["settings.password"] = "パスワード",
                ["settings.encryption"] = "セキュリティ",
                ["settings.encryptTransport"] = "転送を暗号化（信頼できるネットワークではオフにして CPU を節約）",
                ["settings.input"] = "入力",
                ["settings.scroll"] = "スクロール",
                ["settings.modifierKeys"] = "受信キー割り当て",
                ["settings.mapShift"] = "Shift",
                ["settings.mapControl"] = "Control",
                ["settings.mapAlt"] = "Alt",
                ["settings.mapMeta"] = "Win/Mac",
                ["settings.client"] = "子デバイス",
                ["settings.server"] = "サーバー",
                ["settings.enableInputSharing"] = "入力共有を有効化",
                ["settings.reverseVerticalScroll"] = "垂直スクロールを反転",
                ["settings.save"] = "保存",
                ["settings.cancel"] = "キャンセル",
                ["settings.hostClientHint"] = "サーバーに表示された LAN IP を入力してください。",
                ["settings.hostServerHint"] = "同じ LAN のクライアントにこのアドレスを共有してください。",
                ["settings.copyAddress"] = "アドレスをコピー",
                ["settings.copyPassword"] = "パスワードをコピー",
                ["settings.validationHost"] = "この子デバイスが接続するサーバーの LAN アドレスを入力してください。",
                ["settings.validationLoopback"] = "127.0.0.1 ではなくサーバーの LAN IP を使用してください。",
                ["settings.validationPassword"] = "すべてのデバイスで同じ同期パスワードを入力してください。",
                ["settings.confirmNoEncryption"] = "クリップボードと入力データは暗号化されずに送信され、同期パスワードで認証のみ行われます。信頼できるネットワークでのみ使用してください。続行しますか？",
                ["layout.title"] = "画面レイアウト",
                ["layout.subtitle"] = "実際の配置に合わせて各画面をドラッグしてください。",
                ["layout.done"] = "完了",
                ["layout.disconnected"] = "切断済み",
                ["layout.inputDisabled"] = "入力共有オフ",
                ["layout.thisDevice"] = "このデバイス",
                ["layout.autoArrange"] = "自動整列",
                ["layout.saved"] = "レイアウトを保存しました",
                ["layout.forgetDevice"] = "このデバイスを削除",
                ["layout.forgetConfirm"] = "このオフラインデバイスと保存済み画面を削除しますか？",
                ["modifier.shift"] = "Shift",
                ["modifier.control"] = "Control",
                ["modifier.alt"] = "Alt/Option",
                ["modifier.meta"] = "Win/Command",
                ["updates.notConfigured"] = "自動更新はまだ設定されていません。リリース前に NetSparkle Ed25519 キーペアを生成し、Windows アップデーターの公開鍵を置き換えてください。",
                ["status.betaExpired"] = "ベータ終了、更新が必要です",
                ["beta.expiredTitle"] = "ベータ期間終了",
                ["beta.expiredMessage"] = "このベータビルドの30日間の試用期間が終了しました。引き続きご利用いただくにはアップデートを確認してください。",
                ["beta.checkNowQuestion"] = "今すぐアップデートを確認しますか？"
            }
        };

    public static string Text(string key)
    {
        if (Values.TryGetValue(CurrentLanguage, out var localized) && localized.TryGetValue(key, out var value))
        {
            return value;
        }
        return Values[Language.English].TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(string key, params object?[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Text(key), args);
    }

    public static string EdgeTitle(ScreenEdge edge)
    {
        return Text(edge switch
        {
            ScreenEdge.Left => "edge.left",
            ScreenEdge.Top => "edge.top",
            ScreenEdge.Bottom => "edge.bottom",
            _ => "edge.right"
        });
    }

    public static string ModifierTitle(KeyboardModifier modifier)
    {
        return Text(modifier switch
        {
            KeyboardModifier.Control => "modifier.control",
            KeyboardModifier.Alt => "modifier.alt",
            KeyboardModifier.Meta => "modifier.meta",
            _ => "modifier.shift"
        });
    }

    private static Language ResolveLanguage()
    {
        var name = CultureInfo.CurrentUICulture.Name.ToLowerInvariant();
        if (name.StartsWith("zh", StringComparison.Ordinal))
        {
            return Language.Chinese;
        }
        if (name.StartsWith("ko", StringComparison.Ordinal))
        {
            return Language.Korean;
        }
        if (name.StartsWith("ja", StringComparison.Ordinal))
        {
            return Language.Japanese;
        }
        return Language.English;
    }
}
